### PR TITLE
Implement report filtering

### PR DESCRIPTION
**Pull request by mjurkus**
Filtering by type and status or multiple statuses or multiple types.

Later, on demand will add more filtering criterias.

### CODE REVIEW

**Review by tadaskay — APPROVED** [review]
Code looks 👍 

Small thing: some of the files don't end with a new line character, which they should.

**Comment by mjurkus** [comment]
Yeah, we need to add style check

**Comment by mjurkus** [comment]
@tadaskay what's wrong with travis?

**Comment by tadaskay** [comment]
In this case it looks like it was a random connection error (while downloading the gem). Let's squash and merge this.

**Pull request merged**
