### PR TITLE
Simple token authentication for anonymous users

### PR DESCRIPTION
**Pull request by tadaskay**
Anonymous users can acquire an authentication token using `GET /user/token`. This token is to be later placed in `X-Auth-Token` header.
User resource is kind of empty for now, but authenticated users should be able to access `GET /user` (user's own profile).

### CODE REVIEW

**Comment by eimantas** [comment]
I don't want to be picky, but IMHO the header should be just `X-Auth`.

**Comment by spastai** [comment]
Pridetas headeris gerai, bet galbut as kazko nesuprantu, bet token'a clientas turetu gauti ne is backend'o, o is oauth serverio:
https://github.com/spastai/tvarkau-vilniu-ms/wiki/Architecture

**Comment by tadaskay** [comment]
@spastai This is for anonymous use case (which per agreement we're implementing first), without OAuth. BTW please add these diagrams to wiki on main repository instead of the fork.

@eimantas AFAIK this is non-standard header so it's up to application to choose the name, and as far as I checked lots of software do use `X-Auth-Token` for this purpose. Please elaborate why you think  `X-Auth` would be a better choice.

**Comment by tadaskay** [comment]
Merging as there were no objections.

**Comment by ViliusKraujutis** [comment]
> lots of software do use X-Auth-Token for this purpose.

AFAIK, that's true, so `X-Auth-Token` is :+1: for me.

**Comment by spastai** [comment]
Keep in mind that this X-Auth-Token is for app. For user we will have to use 
Authorization: Bearer xxxxxxx
(see https://tools.ietf.org/html/rfc6750#page-4). 
This should be emphasized some how (at least in code comments).

In such case I would modify acquireToken by adding argument deviceId (this could be IMEI)
This would help to control throttle cases - if some deviceId start to send a lot of requests it would be possible to reject them.
If offender fakes deviceId, by providing randomized values - it would be possible to reject new deviceId for some time.

**Comment by tadaskay** [comment]
@spastai The idea is rather much simplier: hand out authorization grant token (think: create user) and let him authenticate using the returned token. It can be later improved security-wise by:
1. Giving out an additional access-token with a shorter validity period
2. HMAC

OAuth is what we want to use for validating user details, but it should not be tightly coupled. Regarding deviceId - it could be one of the before-mentioned user details, but strictly optional due to the nature of different types of devices being able to use the API.

Shortly speaking, the confusing part that probably was not made clear: there are 2 kinds of tokens, one for authorization and authentication (for accessing protected API resources) and another one - OAuth - for validating user details with 3rd party.

As for throttling, it can be simply user based and IP based.

**Pull request merged**
