### PR TITLE
Remove report registred_at

### PR DESCRIPTION
**Pull request by laurynas**
@mjurkus 

Added `created_at` to the report serializer. Also parking report will no longer require to pass `registered_at`.

https://github.com/vilnius/tvarkau-vilniu-ms/issues/109

### CODE REVIEW

**Comment by mjurkus** [comment]
I will need to double check with the old app, but I think we need `violation_timestamp` or something else where we need specific timestamp of violation. Since `registered_at` is not the same as `violation time`. Since many users just take photos of violation and report it later.

**Comment by laurynas** [comment]
Ok, then probably we need to rename `registered_at` to `violation_timestamp`.

**Comment by mjurkus** [comment]
Yep, parking violation needs possibility to specify exact time.

image

**Comment by laurynas** [comment]
Closing in favour of https://github.com/vilnius/tvarkau-vilniu-ms/pull/112

**Pull request closed without merging**
